// Code generated by scripts/codegen/page-layout-registry. DO NOT EDIT.
// Source: packages/sdk-ts/src/meta/layout/control-registry.json
package metamodel

// BuiltInControls is the allow-list of field control slugs shipped by
// @proteos/ui's PageLayoutRenderer. Customer-authored UI blocks use
// ComponentElement.componentSlug, not this list.
var BuiltInControls = []string{
	"checkbox",
	"chip-group",
	"currency",
	"date-picker",
	"datetime-picker",
	"email",
	"entity-picker",
	"file",
	"file-viewer",
	"knowledge-text",
	"multi-select",
	"number",
	"password",
	"radio-group",
	"select",
	"switch",
	"tag-input",
	"text",
	"textarea",
	"time-picker",
	"url",
	"user-picker",
}

// IsBuiltInControl reports whether slug is in BuiltInControls.
func IsBuiltInControl(slug string) bool {
	for _, c := range BuiltInControls {
		if c == slug {
			return true
		}
	}
	return false
}

// ControlBucket declares the primary control slug and the full compatible
// list for one (type[+format|+items.type]) combination. A nil Primary and
// empty Compatible means "render-only fallback" — no editor is available
// for that attribute combination.
type ControlBucket struct {
	Primary    *string
	Compatible []string
}

// ControlsByAttributeType maps a Go-canonical attribute type to its bucket.
var ControlsByAttributeType = map[string]ControlBucket{
	"array":          {Primary: stringPtr("tag-input"), Compatible: []string{"tag-input"}},
	"boolean":        {Primary: stringPtr("switch"), Compatible: []string{"switch", "checkbox"}},
	"currency":       {Primary: stringPtr("currency"), Compatible: []string{"currency"}},
	"datetime":       {Primary: nil, Compatible: []string{}},
	"enum":           {Primary: stringPtr("select"), Compatible: []string{"select", "radio-group", "chip-group"}},
	"file":           {Primary: stringPtr("file"), Compatible: []string{"file", "file-viewer"}},
	"integer":        {Primary: stringPtr("number"), Compatible: []string{"number"}},
	"knowledge-text": {Primary: stringPtr("knowledge-text"), Compatible: []string{"knowledge-text"}},
	"number":         {Primary: stringPtr("number"), Compatible: []string{"number"}},
	"object":         {Primary: nil, Compatible: []string{}},
	"relation":       {Primary: stringPtr("entity-picker"), Compatible: []string{"entity-picker"}},
	"string":         {Primary: stringPtr("text"), Compatible: []string{"text", "textarea", "password"}},
	"user":           {Primary: stringPtr("user-picker"), Compatible: []string{"user-picker"}},
}

// ControlsByStringFormat maps StringFormat values to their bucket.
var ControlsByStringFormat = map[string]ControlBucket{
	"email":    {Primary: stringPtr("email"), Compatible: []string{"email", "text"}},
	"hostname": {Primary: stringPtr("text"), Compatible: []string{"text"}},
	"ipv4":     {Primary: stringPtr("text"), Compatible: []string{"text"}},
	"ipv6":     {Primary: stringPtr("text"), Compatible: []string{"text"}},
	"uri":      {Primary: stringPtr("url"), Compatible: []string{"url", "text"}},
	"uuid":     {Primary: stringPtr("text"), Compatible: []string{"text"}},
}

// ControlsByDatetimeFormat maps DatetimeFormat values to their bucket.
var ControlsByDatetimeFormat = map[string]ControlBucket{
	"date":      {Primary: stringPtr("date-picker"), Compatible: []string{"date-picker"}},
	"date-time": {Primary: stringPtr("datetime-picker"), Compatible: []string{"datetime-picker"}},
	"duration":  {Primary: nil, Compatible: []string{}},
	"time":      {Primary: stringPtr("time-picker"), Compatible: []string{"time-picker"}},
}

// ControlsByArrayItemsType maps the item Attribute's type to the array
// bucket the renderer should use for that array-of-X combination.
var ControlsByArrayItemsType = map[string]ControlBucket{
	"enum":   {Primary: stringPtr("multi-select"), Compatible: []string{"multi-select"}},
	"string": {Primary: stringPtr("tag-input"), Compatible: []string{"tag-input"}},
}

func stringPtr(s string) *string { return &s }
